Modularized configure script.
It's now split out into functions, and the first function to execute is intuitively placed at the top of the file. Most importantly, a dedicated 'writeLine' function is used to write lines to the Makefile being generated.

Also, a check was added so that the script aborts with an error if a subproject fails to create a Makefile after its script returns.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# BashBuild v0.1.0 "Feature Complete"
+# BashBuild v0.1.1 "Prettier"
 #
 # BashBuild is a minimal build system implemented entirely in the configure script.
 #  Project setup is performed by modifying the variables at the top of the script.
@@ -25,110 +25,170 @@ PREFIX="/usr/local"
 CCFLAGS="-c -Wall -g"
 LDFLAGS=""
 
-# Autodetect compiler paths
-C_COMPILER=""
-if [ -z "$C_COMPILER" ]; then C_COMPILER=`which gcc`; fi;
-if [ -z "$C_COMPILER" ]; then C_COMPILER=`which cc`; fi;
+# --- User Variables End Here --- #
 
-CPP_COMPILER=""
-if [ -z "$CPP_COMPILER" ]; then CPP_COMPILER=`which g++`; fi;
-if [ -z "$CPP_COMPILER" ]; then CPP_COMPILER=`which c++`; fi;
+function main () {
+    detectCompiler
+    detectPaths
+    parseArguments
+    calcFilename
 
-while getopts "p:c:" Option
-do
-    case $Option in
-	p ) PREFIX="$OPTARG";;
-	c ) C_COMPILER=`which $OPTARG`;;
-        * ) echo "./configure [-h] [-p install-prefix] [-c c-compiler]" >2;;
+    subprojectsConfigure
+
+    startOutput
+
+    # Print header
+    writeLine "# Makfile for project: $PROJECT"
+    writeLine "#   Generated by BashBuild v0.1.1"
+    writeLine "#   On $(date)"
+
+    writeVariables
+    writeBuildRules
+
+    stopOutput
+}
+
+# --- Autodetection Functions --- #
+function detectCompiler () {
+    # Autodetect compiler paths
+    C_COMPILER=""
+    if [ -z "$C_COMPILER" ]; then C_COMPILER=`which gcc`; fi;
+    if [ -z "$C_COMPILER" ]; then C_COMPILER=`which cc`; fi;
+
+    CPP_COMPILER=""
+    if [ -z "$CPP_COMPILER" ]; then CPP_COMPILER=`which g++`; fi;
+    if [ -z "$CPP_COMPILER" ]; then CPP_COMPILER=`which c++`; fi;
+}
+
+function detectPaths () {
+    # Autodetect source file main directory
+    PROJDIR=`which $0 | sed 's/configure//'`
+    BUILDDIR=`pwd`
+}
+
+
+# --- Parse the command-line arguments to ./configure --- #
+function parseArguments () {
+    while getopts "p:c:" Option
+    do
+	case $Option in
+	    p ) PREFIX="$OPTARG";;
+	    c ) C_COMPILER=`which $OPTARG`;;
+            * ) echo "./configure [-h] [-p install-prefix] [-c c-compiler]" >2;;
+	esac
+    done
+}
+
+
+# --- Calculate the filename for the resulting binary --- #
+function calcFilename () {
+    # Determine output file name
+    BINARY="$PROJECT"
+    if [ "$OUTPUT" == "shared" ]; then BINARY="lib$PROJECT.so"; fi;
+    if [ "$OUTPUT" == "static" ]; then BINARY="lib$PROJECT.a"; fi;
+}
+
+
+# --- Recursively run the subproject configure scripts --- #
+function subprojectsConfigure () {
+    for dir in $SUBPROJECTS; do
+	mkdir -p "$dir" && cd "$dir" && "$PROJDIR"/"$dir"/configure -p "$PREFIX" -c "C_COMPILER"
+	cd "$BUILDDIR"
+	echo "$BUILDDIR/$dir/Makefile"
+	if [ ! -f "$BUILDDIR/$dir/Makefile" ]
+	then
+	    echo "Error: Unable to configure subproject $dir">&2
+	    exit
+	fi
+    done
+}
+
+# --- Various output functions --- #
+function writeVariables () {
+    # Print some important variables
+    writeLine "PROJECT=$PROJECT"
+    writeLine "VERSION=$VERSION"
+    writeLine "LFLAGS=$LDFLAGS \$(foreach i,$LIBDIRS,-L\$(i)) \$(foreach i,$LIBRARIES,-l\$(i))"
+    writeLine "CFLAGS=$CCFLAGS \$(foreach i,$INCDIRS,-I\$(i))"
+    writeLine "SUBPROJECTS=$SUBPROJECTS"
+    writeLine "SOURCES=\$(foreach i,$SOURCES,$PROJDIR/\$(i))"
+    writeLine "SOURCES_TMP=\$(foreach i,$SOURCES,$BUILDDIR/\$(i))"
+    writeLine "OBJECTS_BLD=\$(SOURCES_TMP:.c=.o)"
+}
+
+function writeBuildRules () {
+    writeBuildAll
+    writeBuildBinary
+    writeBuildObjects
+    writeBuildSubprojects
+    writeBuildExtra
+}
+
+function writeBuildAll () {
+    writeLine "all: \$(SOURCES_PRJ) $BINARY"
+}
+
+function writeBuildBinary () {
+    writeLine "$BINARY: \$(OBJECTS_BLD) \$(SUBPROJECTS)"
+    writeLine "ifdef SOURCES"
+    case "$OUTPUT" in
+	shared) writeLine "	$C_COMPILER -shared \$(OBJECTS_BLD) \$(LFLAGS) -o $BINARY";;
+	static) writeLine "	ar rcs $BINARY \$(OBJECTS_BLD)";;
+	*     ) writeLine "	$C_COMPILER \$(OBJECTS_BLD) \$(LFLAGS) -o $BINARY";;
     esac
-done
+    writeLine "endif"
+}
 
-# Autodetect source file main directory
-PROJDIR=`which $0 | sed 's/configure//'`
-BUILDDIR=`pwd`
+function writeBuildObjects () {
+    writeLine  "$BUILDDIR/%.o: $PROJDIR/%.c"
+    writeLine  "	$C_COMPILER \$(CFLAGS) -fPIC \$< -o \$@"
+}
 
-# Determine output file name
-BINARY="$PROJECT"
-if [ "$OUTPUT" == "shared" ]; then BINARY="lib$PROJECT.so"; fi;
-if [ "$OUTPUT" == "static" ]; then BINARY="lib$PROJECT.a"; fi;
+function writeBuildSubprojects () {
+    writeLine  "\$(SUBPROJECTS):"
+    writeLine  "	make -C \$@"
+}
 
-TMPFILE="Makefile.partial"
+function writeBuildExtra () {
+    # The install rule
+    writeLine  "install:"
+    writeLine  "	@ for i in \$(SUBPROJECTS); do make -C \$\${i} install; done"
+    case "$OUTPUT" in
+	shared | static) writeLine "	install $BINARY $PREFIX/lib";;
+	*              ) writeLine "	install $BINARY $PREFIX/bin";;
+    esac
 
-# Remove old makefile residue
-rm -f Makefile "$TMPFILE"
+    writeLine  "tidy:"
+    writeLine  "	@ for i in \$(SUBPROJECTS); do make -C \$\${i} tidy; done"
+    writeLine  "	rm -f \$(OBJECTS_BLD)"
 
-# Print header
-echo "
-# Makfile for project: $PROJECT
-#   Generated by BashBuild v0.1.0
-#   On" `date` >> "$TMPFILE"
+    writeLine  "clean:"
+    writeLine  "	@ for i in \$(SUBPROJECTS); do make -C \$\${i} clean; done"
+    writeLine  "	rm -f \$(OBJECTS_BLD) $BINARY"
 
-# Print important variables
-echo "
-PROJECT=$PROJECT
-VERSION=$VERSION
-LFLAGS=$LDFLAGS \$(foreach i,$LIBDIRS,-L\$(i)) \$(foreach i,$LIBRARIES,-l\$(i))
-CFLAGS=$CCFLAGS \$(foreach i,$INCDIRS,-I\$(i))
+    writeLine  "distclean:"
+    writeLine  "	@ for i in \$(SUBPROJECTS); do make -C \$\${i} distclean; done"
+    writeLine  "	rm -f \$(OBJECTS_BLD) $BINARY Makefile"
 
-SUBPROJECTS=$SUBPROJECTS
+    writeLine  ".PHONY: install tidy clean distclean \$(SUBPROJECTS)"
+}
 
-SOURCES=\$(foreach i,$SOURCES,$PROJDIR/\$(i))
-SOURCES_TMP=\$(foreach i,$SOURCES,$BUILDDIR/\$(i))
-OBJECTS_BLD=\$(SOURCES_TMP:.c=.o)
-" >> "$TMPFILE"
+# --- Output Functions --- #
+function startOutput () {
+    TMPFILE="Makefile.partial"
+    rm -f Makefile "$TMPFILE"
+}
 
-# Print main rules
-echo "
-all: \$(SOURCES_PRJ) $BINARY
+function writeLine () {
+    echo "$1" >> "$TMPFILE"
+}
 
-$BINARY: \$(OBJECTS_BLD) \$(SUBPROJECTS)
-ifdef SOURCES" >> "$TMPFILE"
-if      [ "$OUTPUT" == "shared" ]
-    then echo "	$C_COMPILER -shared \$(OBJECTS_BLD) \$(LFLAGS) -o $BINARY" >> "$TMPFILE"
-else if [ "$OUTPUT" == "static" ];
-    then echo "	ar rcs $BINARY \$(OBJECTS_BLD)" >> "$TMPFILE"
-    else echo "	$C_COMPILER \$(OBJECTS_BLD) \$(LFLAGS) -o $BINARY" >> "$TMPFILE"
-fi; fi;
-echo "endif # (SOURCES)" >> "$TMPFILE"
+function stopOutput () {
+    # Move the temporary makefile to the real one
+    mv "$TMPFILE" Makefile
+}
 
-# Print source file inference rule and subproject build rule
-echo "
-$BUILDDIR/%.o: $PROJDIR/%.c
-	$C_COMPILER \$(CFLAGS) -fPIC \$< -o \$@
-
-\$(SUBPROJECTS):
-	make -C \$@" >> "$TMPFILE"
-
-echo "install:
-	@ for i in \$(SUBPROJECTS); do make -C \$\${i} install; done" >> "$TMPFILE"
-if [[ "$OUTPUT" == "shared" || "$OUTPUT" == "static" ]]
-then
-    echo "	install $BINARY $PREFIX/lib" >> "$TMPFILE"
-else
-    echo "	install $BINARY $PREFIX/bin" >> "$TMPFILE"
-fi
-
-# Miscellaneous Build Targets
-echo "
-tidy:
-	@ for i in \$(SUBPROJECTS); do make -C \$\${i} tidy; done
-	rm -f \$(OBJECTS_BLD)
-clean:
-	@ for i in \$(SUBPROJECTS); do make -C \$\${i} clean; done
-	rm -f \$(OBJECTS_BLD) $BINARY
-distclean:
-	@ for i in \$(SUBPROJECTS); do make -C \$\${i} distclean; done
-	rm -f \$(OBJECTS_BLD) $BINARY Makefile
-
-.PHONY: install tidy clean distclean \$(SUBPROJECTS)" >> "$TMPFILE"
-
-for dir in "$SUBPROJECTS"
-do
-    mkdir -p "$dir" && cd "$dir" && "$PROJDIR"/"$dir"/configure -p "$PREFIX" -c "C_COMPILER"
-    cd "$BUILDDIR"
-done
-
-# Move the temporary makefile to the real one
-mv "$TMPFILE" Makefile
+# And finally, call the main() function to make everything run
+main
 
 # BashBuild Copyright (c) 2009 Will Donnelly <will.donnelly@gmail.com>
